# Bike Rental Forecasting using LSTM based Network #


In [1]:
import numpy as np
from numpy import newaxis
import keras
import datetime
import random
from keras.models import Sequential
from keras.layers import Activation, Dropout, Flatten, Dense, LSTM, TimeDistributed
from sklearn import metrics as mt

import pandas as pd
from keras import optimizers
import datetime

slidingwindow = 12
maxval_w = 1
maxval_pb = 1

Using TensorFlow backend.


## Data Preparation ##

In [2]:
def parse_data(df, window_sz):
    data = np.squeeze(np.reshape(df, newshape= [-1,1]), axis=1)
    
    init = np.zeros(window_sz)
    result=[]
    data = np.append(init,data)
    #print(data[0:34])
    
    for index in range(window_sz,len(data)):
        tmp=[]
        tmp = data[index-window_sz:index]
        #tmp = data[2:14]
        rsed_arr = tmp[::-1]
        #result.append(np.append([data[index]],tmp))
        result.append(rsed_arr)
    result=np.array(result)
    print(result.shape)
    
    return result

In [3]:
def load_data(fname):
    global noballs, slidingwindow, norm_wndw
    print("*** loading data ***")
    df = pd.read_csv(fname)

    data = np.array(df.iloc[:, 12])
    
    trainX = parse_data(data, slidingwindow)
    df = np.concatenate((trainX,df), axis=1)

    print("Data has size of ", data.shape)
    print("Sample data on how lag features look for the forecast:\n",trainX[0:20:,])
    return df

In [14]:
preppeddata=load_data("Regression_ Demand estimation.csv")

*** loading data ***
(17379, 12)
Data has size of  (17379,)
Sample data on how lag features look for the forecast:
 [[   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [  16.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [  40.   16.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [  32.   40.   16.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [  13.   32.   40.   16.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   1.   13.   32.   40.   16.    0.    0.    0.    0.    0.    0.    0.]
 [   1.    1.   13.   32.   40.   16.    0.    0.    0.    0.    0.    0.]
 [   2.    1.    1.   13.   32.   40.   16.    0.    0.    0.    0.    0.]
 [   3.    2.    1.    1.   13.   32.   40.   16.    0.    0.    0.    0.]
 [   8.    3.    2.    1.    1.   13.   32.   40.   16.    0.    0.    0.]
 [  14.    8.    3.    2.    1.    1.   13.   32.   40.   16.    0.    0.]
 [  36.   14.    8.    3.    2.    1.    1.   13.   32.   4

In [15]:
def createDataset(df):
    row = int(0.89971*df.shape[0])
    traindf = df[0:row,:]
    testdf = df[row:,:]
    trainY=traindf[:,-1]
    trainX=traindf[:,:-1]
    testY = testdf[:,-1]
    testX = testdf[:,:-1]
    return trainX, trainY, testX, testY

In [16]:
trX, trY, tsX, tsY = createDataset(preppeddata)

In [17]:
print("train X shape", trX.shape)
print("train Y shape", trY.shape)
print("test X shape", tsX.shape)
print("test Y shape", tsY.shape)

train X shape (15636, 24)
train Y shape (15636,)
test X shape (1743, 24)
test Y shape (1743,)


## Training ##

In [18]:
def hyper_parameters(window_sz):
    global units, dropouts, layers, outputunits, input_dim, batch_sz, numepochs
    unitset  = [96, 96, 96, 96]
    layerset = [1, 1, 1, 1, 1]
    dropoutset = [0.4,0.4,0.4]
    
    layers = random.choice(layerset)
    units = np.zeros(layers)
    dropouts = np.zeros(layers)
    batch_sz = 96
    for i in range(0, layers):
        units[i] = random.choice(unitset)
        dropouts[i] = random.choice(dropoutset)
    units[0] = batch_sz
    
    outputunits = 1
    
    numepochs = 10
    
    print(layers)
    print(units)
    print(dropouts)

Try creating network without dropouts. 

In [19]:
def setupNetwork(window_sz):
    global units, dropouts, layers, outputunits
    model = Sequential()

    timestamps = 1
    features = 24

    model.add(keras.layers.LSTM(units=units[0].astype("int64"), return_sequences=False, input_shape=(features, timestamps)))
    #model.add(Dropout(dropouts[0]))
    model.add(Dense(units=batch_sz*2))
    model.add(Activation('relu'))
    model.add(Dense(timestamps))
    model.add(Activation('linear'))

    model.compile(loss='mse', optimizer='rmsprop')
    return model

In [20]:
hyper_parameters(slidingwindow)
model = setupNetwork(slidingwindow)
print(model.summary())

1
[ 96.]
[ 0.4]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 96)                37632     
_________________________________________________________________
dense_3 (Dense)              (None, 192)               18624     
_________________________________________________________________
activation_3 (Activation)    (None, 192)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 193       
_________________________________________________________________
activation_4 (Activation)    (None, 1)                 0         
Total params: 56,449
Trainable params: 56,449
Non-trainable params: 0
_________________________________________________________________
None


In [21]:
def trainModel(m, xtr, ytr, ep, bsz,l=0):
    

    m.fit(xtr, ytr, batch_size=bsz, epochs=ep, validation_split=0.079, verbose=l)
    return m

In [320]:
global batch_sz
print(batch_sz)
modelrest = trainModel(model, trX.reshape(-1,24,1), trY.reshape(-1,1), 1, batch_sz,2)

96
Train on 14400 samples, validate on 1236 samples
Epoch 1/1
6s - loss: 33261.0362 - val_loss: 48652.8404


## Model Evaluation ##

In [22]:
def compute_perf(m, xts, yts):
    ypred = m.predict(xts.reshape(xts.shape[0],24,-1))
    py = np.squeeze(np.reshape(ypred, newshape= [-1,1]), axis=1)
    r2 = mt.r2_score(yts, ypred)
    #print(r2)
    return r2

Run parameter sweep across batch and epoch to find the best parameters that give best R^2 value

In [23]:
def parameter_sweep():
    marr = np.empty((8,5), dtype=Sequential)
    r2 = np.zeros((8,5))
    rowcnt = 0
    colcnt = 0
    print("------------------------------------------------------")
    print("|     R^2    |            epochs                     |")
    print("------------------------------------------------------")
    print("| batch size | ",end="")
    for e in range(2,12,2):
        print(" %3d  | "% e, end="")
    print()
    print("------------------------------------------------------")
    for b in range(24,192,24):
        colcnt = 0
        print("|   %3d      |"% b, end="")
        for e in range(2,12,2):
            mtmp = setupNetwork(slidingwindow)
            marr[rowcnt, colcnt] = trainModel(mtmp, trX.reshape(-1,24,1), trY.reshape(-1,1), e, b, 0)
            r2[rowcnt, colcnt] = compute_perf(marr[rowcnt, colcnt], tsX, tsY)
            
            r = r2[rowcnt, colcnt]
            print(" %0.4f|"% r,end="")
            colcnt += 1
            #print("batch size = ", b, " epochs = ", e, " r^2 = ", r2[rowcnt, colcnt])
        rowcnt +=1
        print()
    print("------------------------------------------------------")

The comparable data using 12 lag features when trained on Azure ML v1 using Boosted decision tree gives R-Square value of 0.82. 

Running parameter sweep across various batch sizes and epochs taks almost 30 mins on 1 GPU based VM. So only run the cell below if you have 30 mins. Else use the data from my run as shown below which shows that batch size with 48 for 10 epochs gives the best result of R^2 being **0.8936** or use 24 batch size with 6 epochs for decent R^2 of **0.8711**. 

![](http://neerajkh.blob.core.windows.net/images/parametersweep_bikerental.PNG)


In [326]:
start = datetime.datetime.now()
print("start of parameter sweep:", start)
#parameter_sweep()
end = datetime.datetime.now()
print("end of parameter sweep:", end)
print("total time = ", end-start)

start of parameter sweep: 2017-08-17 06:58:03.419863
------------------------------------------------------
|     R^2    |            epochs                     |
------------------------------------------------------
| batch size |    2  |    4  |    6  |    8  |   10  | 
------------------------------------------------------
|    24      | 0.7883| 0.8528| 0.8711| 0.8650| 0.8869|
|    48      | 0.7416| 0.8680| 0.8608| 0.8122| 0.8936|
|    72      | 0.5781| 0.7339| 0.8339| 0.8421| 0.8768|
|    96      | 0.4999| 0.8006| 0.8537| 0.8328| 0.8344|
|   120      | 0.5199| 0.7757| 0.6741| 0.8744| 0.8855|
|   144      | 0.5152| 0.5872| 0.8151| 0.7679| 0.8827|
|   168      | 0.4721| 0.4786| 0.7987| 0.5265| 0.8289|
------------------------------------------------------
end of parameter sweep: 2017-08-17 07:28:01.795318
total time =  0:29:58.375455


Running parameter sweep also provided hint that we can combine various batch sizes and epochs to get the best results. Here is the one way to do it

In [24]:
def trainWithVaryingBatchAndEpochs(m):
    
    b = 24
    for e in range(2,8,2):      
        m = trainModel(m, trX.reshape(-1,24,1), trY.reshape(-1,1), e, b, 0)
        r2 = compute_perf(m, tsX, tsY)
        print("At end of epoch %d "% e, end="")
        print("using batch size of %d "% b, end="")
        print("the r^2 is %0.4f|"% r2)
    b = 48
    e = 2
    m = trainModel(m, trX.reshape(-1,24,1), trY.reshape(-1,1), e, b, 0)
    print("At end of epoch %d "% e, end="")
    print("using batch size of %d "% b, end="")
    print("the r^2 is %0.4f|"% r2)
    e = 4
    m = trainModel(m, trX.reshape(-1,24,1), trY.reshape(-1,1), e, b, 0)
    print("At end of epoch %d "% e, end="")
    print("using batch size of %d "% b, end="")
    print("the r^2 is %0.4f|"% r2)
    return m
        

In [25]:
mtmp = setupNetwork(slidingwindow)
#mtmp = trainWithVaryingBatchAndEpochs(mtmp)

Now we can try to see if dropouts improve accuracy or not. So we will add dropouts with above configuration and try the new network with dropouts

In [26]:
def setupNetworkWithDropouts(window_sz):
    global units, dropouts, layers, outputunits
    model = Sequential()

    timestamps = 1
    features = 24

    model.add(keras.layers.LSTM(units=units[0].astype("int64"), return_sequences=False, input_shape=(features, timestamps)))
    model.add(Dropout(0.5))
    model.add(Dense(units=batch_sz*2, activation='relu'))
    
    model.add(Dropout(0.5))
    model.add(Dense(timestamps, activation='linear'))
    

    model.compile(loss='mse', optimizer='rmsprop')
    return model

In [29]:
anothermodel = setupNetworkWithDropouts(slidingwindow)
anothermodel = trainWithVaryingBatchAndEpochs(anothermodel) 

At end of epoch 2 using batch size of 24 the r^2 is 0.8170|
At end of epoch 4 using batch size of 24 the r^2 is 0.8628|
At end of epoch 6 using batch size of 24 the r^2 is 0.8045|
At end of epoch 2 using batch size of 48 the r^2 is 0.8045|
At end of epoch 4 using batch size of 48 the r^2 is 0.8045|


Now that we have tried all alternatives, progressive batch/epoch, dropout etc., the simplest model that provides good accuracy is with batch size 48 and epoch 10. So for now, we will go with that model. 

For now, let's go with batch size of 48 and 10 epochs with no dropouts.

In [29]:
finalmodel = setupNetwork(slidingwindow)
finalmodel = trainModel(model, trX.reshape(-1,24,1), trY.reshape(-1,1), 10, 48,2)

Train on 14400 samples, validate on 1236 samples
Epoch 1/10
10s - loss: 2867.1916 - val_loss: 4776.4148
Epoch 2/10
10s - loss: 2707.0263 - val_loss: 5978.1012
Epoch 3/10
10s - loss: 2546.9158 - val_loss: 6757.7123
Epoch 4/10
10s - loss: 2465.9893 - val_loss: 5897.2418
Epoch 5/10
9s - loss: 2421.4319 - val_loss: 5742.7474
Epoch 6/10
10s - loss: 2374.0229 - val_loss: 6649.3893
Epoch 7/10
9s - loss: 2264.1990 - val_loss: 9086.7461
Epoch 8/10
10s - loss: 2249.5384 - val_loss: 6196.7814
Epoch 9/10
10s - loss: 2191.3645 - val_loss: 5604.7572
Epoch 10/10
9s - loss: 2101.7306 - val_loss: 4273.9195


In [30]:
print("R^2 = ", compute_perf(finalmodel, tsX, tsY))
finalmodel.save("finalmodel.sav")

R^2 =  0.892330549527


## Operationalization ##

Check for existing **scoring file** and if it exist, remove the scoring file

In [31]:
# remove previous bikescore.py
export_path_base = "bikescore.py"
import os
if os.path.exists(export_path_base):
    print("score file already exist, removing score file")
    os.remove(export_path_base)
else:
    print("no score file found - safe to continue")

score file already exist, removing score file


Write init() and run() functions to score.py file using magic commands

In [35]:
%%writefile bikescore.py

import numpy as np
from numpy import newaxis
import keras
from keras.models import Sequential
from keras.layers import Activation, Dropout, Flatten, Dense, LSTM, TimeDistributed
import pandas as pd

def init():
    global trainedmod
    from keras.models import load_model
    
    trainedmod = load_model("finalmodel.sav")

Overwriting bikescore.py


In [38]:
%%writefile -a bikescore.py

def run(npa):
    global trainedmod
    
    if (len(npa.shape) > 1):
        ypred = trainedmod.predict(npa.reshape(npa.shape[0],24,1))
    else:
        ypred = trainedmod.predict(npa.reshape(1,24,1))
    retdf = pd.DataFrame(data={"Scored Values":np.squeeze(np.reshape(ypred, newshape= [-1,1]), axis=1)})
    return str(retdf)

Appending to bikescore.py


In [39]:
def testsavedmodel():
    global trainedmod
    print("R^2 = ", compute_perf(finalmodel, tsX, tsY))

In [46]:
import bikescore
bikescore.init()
testsavedmodel()

R^2 =  0.892330549527


Now we have verified that we have loaded correct model as R^2 value of model saved above is same as the model loaded from the file

In [47]:
print(tsX[1,:])

[  8.90000000e+02   4.50000000e+02   3.53000000e+02   2.85000000e+02
   3.32000000e+02   3.77000000e+02   2.68000000e+02   2.18000000e+02
   3.87000000e+02   8.34000000e+02   5.08000000e+02   1.53000000e+02
   4.00000000e+00   1.00000000e+00   1.00000000e+01   1.80000000e+01
   0.00000000e+00   4.00000000e+00   1.00000000e+00   2.00000000e+00
   5.60000000e-01   5.30300000e-01   6.40000000e-01   3.28400000e-01]


In [48]:
predY = bikescore.run(tsX[0:5,:])
trueY=str(pd.DataFrame(data={"Actual Values":np.squeeze(np.reshape(tsY[0:5], newshape= [-1,1]), axis=1)}))

In [49]:
for x,y in zip(predY.split('\n'),trueY.split('\n')):
    print(x.strip(), "\t\t\t",y.strip()) 

Scored Values 			 Actual Values
0     818.072937 			 0          890.0
1     853.520874 			 1          788.0
2     559.912903 			 2          513.0
3     451.836731 			 3          387.0
4     266.931793 			 4          283.0


### Generate schema file ###

In [50]:
from azure.ml.api.schema.dataTypes import DataTypes
from azure.ml.api.schema.sampleDefinition import SampleDefinition
import azure.ml.api.realtime.services as amlo16n

In [52]:
inputs = {"npa": SampleDefinition(DataTypes.NUMPY, tsX[0:3,:])}
amlo16n.generate_schema(inputs=inputs,
                            filepath="bikeschema.json",
                            run_func=bikescore.run)
amlo16n.generate_main(user_file="bikescore.py", schema_file="bikeschema.json",
                          main_file_name="main.py")

'main.py'

In [53]:
# check score.py and main.py
%pycat bikescore.py


In [54]:
%pycat main.py

## Setup Environment ##
For cluster deployment, you need to setup you environment with ACS, storage, ACR, AppInsights etc. Cluster deployment expects that you have precreated experimentation and model management account through Ibiza as per instructions in the [Instruction Guide](https://github.com/Azure/ViennaDocs/blob/master/Documentation/Installation.md)

You can validate your account using the command shown below

```
C:\Users\neerajkh\Documents\VIenna\BikeForecastNotebook>az ml account modelmanagement list
{
  "created_on": "2017-08-22T02:34:00.837873Z",
  "description": "",
  "id": "/subscriptions/6d976e3d-6278-4645-ab79-cc5f5fe01a49/resourceGroups/amlviennagrp2/providers/Microsoft.MachineLearningModelManagement/accounts/neerajteam2hosting",
  "location": "eastus2",
  "model_management_swagger_location": "https://eastus2.modelmanagement.azureml.net/api/subscriptions/6d976e3d-6278-4645-ab79-cc5f5fe01a49/resourceGroups/amlviennagrp2/accounts/neerajteam2hosting/swagger.json?api-version=2017-09-01-preview",
  "modified_on": "2017-08-22T02:34:00.837873Z",
  "name": "neerajteam2hosting",
  "resource_group": "amlviennagrp2",
  "sku": {
    "capacity": 1,
    "name": "S1"
  },
  "subscription": "6d976e3d-6278-4645-ab79-cc5f5fe01a49",
  "tags": null,
  "type": "Microsoft.MachineLearningModelManagement/accounts"
}
```

Let's set this account to be the default account for registering models and web services.

```
C:\Users\neerajkh\Documents\VIenna\BikeForecastNotebook>az ml account modelmanagement set -n neerajteam2hosting -g amlviennagrp2
{
  "created_on": "2017-08-22T02:34:00.837873Z",
  "description": "",
  "id": "/subscriptions/6d976e3d-6278-4645-ab79-cc5f5fe01a49/resourceGroups/amlviennagrp2/providers/Microsoft.MachineLearningModelManagement/accounts/neerajteam2hosting",
  "location": "eastus2",
  "model_management_swagger_location": "https://eastus2.modelmanagement.azureml.net/api/subscriptions/6d976e3d-6278-4645-ab79-cc5f5fe01a49/resourceGroups/amlviennagrp2/accounts/neerajteam2hosting/swagger.json?api-version=2017-09-01-preview",
  "modified_on": "2017-08-22T02:34:00.837873Z",
  "name": "neerajteam2hosting",
  "resource_group": "amlviennagrp2",
  "sku": {
    "capacity": 1,
    "name": "S1"
  },
  "subscription": "6d976e3d-6278-4645-ab79-cc5f5fe01a49",
  "tags": null,
  "type": "Microsoft.MachineLearningModelManagement/accounts"
}
```

Once model management account is created, the next step is to create an environment. Users can create K8 based ACS cluster environment using the following commands.

Let's validate if our environment has been created and if so, then let's set it to be the default environment for our implementation.
```
C:\Users\neerajkh\Documents\VIenna\BikeForecastNotebook>az ml env setup -n amlviennacluster -c -l eastus2 -g amlviennagrp2
Subscription set to Channels
Continue with this subscription (Y/n)? Y
Resource group amlviennagrp2 already exists, skipping creation.
waiting for AAD role to propagate.done
Provisioning compute resources...
Resource creation submitted successfully.
Resources may take 10-20 minutes to be completely provisioned.
To see if your environment is ready to use, run:
  az ml env show -g amlviennagrp2 -n amlviennacluster
Once your environment has successfully provisioned, you can set it as your target context using:
  az ml env set -g amlviennagrp2 -n amlviennacluster
C:\Users\neerajkh\Documents\VIenna\BikeForecastNotebook>az ml env list
[
  {
    "Cluster Name": "amlviennacluster",
    "Cluster Size": 2,
    "Created On": "2017-08-22T04:03:09.147000+00:00",
    "Location": "eastus2",
    "Provisioning State": "Succeeded",
    "Resource Group": "amlviennagrp2",
    "Subscription": "6d976e3d-6278-4645-ab79-cc5f5fe01a49"
  }
]
C:\Users\neerajkh\Documents\VIenna\BikeForecastNotebook>az ml env set -n amlviennacluster -g amlviennagrp2
Compute set to amlviennacluster.
```

You are all set with environment


### Create web service ###
Now you can create web service by using command az ml service and passing scoring file, schema file, dependencies file, and model file as shown below


```
neeraj@mygpudsvm:~/notebooks$ az ml service create realtime -f bikescore.py -s bikeschema.json --model-file finalmodel.sav --model-name bikemodel -n bikews -r spark-py -c conda_dependencies.yml -l
Creating new driver at /tmp/tmpguctlak4.py
Uploading dependencies.
 bikescore.py
 finalmodel.sav
 bikeschema.json
 /tmp/tmpnls6y0nk/swagger.json
 /tmp/requirementsn2fm6ktl.txt
 conda_dependencies.yml
Creating docker image..........done.
Image available at : wino16nenvacr.azurecr.io/bikews
[Local mode] Running docker container.
[Local mode] Pulling the image from wino16nenvacr.azurecr.io/bikews. This may take a few minutes, depending on your connection speed...
[Local mode] Pulling...........
[Local mode] Success.
[Local mode] Scoring endpoint: http://127.0.0.1:32789/score
[Local mode] Usage: az ml service run realtime -n bikews -d "!! YOUR DATA HERE !!"
```

### List web service details ###

You can list web service details along with calling pattern by using the following command

```
neeraj@mygpudsvm:~/notebooks$ az ml service show realtime -n bikews
+--------+---------------------------------+-------+----------+----------+-------------+----------+
| NAME   | IMAGE                           | CPU   | MEMORY   | STATUS   |   INSTANCES | HEALTH   |
|--------+---------------------------------+-------+----------+----------+-------------+----------|
| bikews | wino16nenvacr.azurecr.io/bikews | N/A   | N/A      | running  |           1 | N/A      |
+--------+---------------------------------+-------+----------+----------+-------------+----------+
Usage:
  az ml  : az ml service run realtime -n bikews -d "{\"npa\": [[450.0, 353.0, 285.0, 332.0, 377.0, 268.0, 218.0, 387.0, 834.0, 508.0, 153.0, 42.0, 4.0, 1.0, 10.0, 17.0, 0.0, 4.0, 1.0, 2.0, 0.58, 0.5455, 0.64, 0.3284], [890.0, 450.0, 353.0, 285.0, 332.0, 377.0, 268.0, 218.0, 387.0, 834.0, 508.0, 153.0, 4.0, 1.0, 10.0, 18.0, 0.0, 4.0, 1.0, 2.0, 0.56, 0.5303, 0.64, 0.3284], [788.0, 890.0, 450.0, 353.0, 285.0, 332.0, 377.0, 268.0, 218.0, 387.0, 834.0, 508.0, 4.0, 1.0, 10.0, 19.0, 0.0, 4.0, 1.0, 2.0, 0.56, 0.5303, 0.68, 0.2985]]}"
  curl : curl -X POST -H "Content-Type:application/json" --data "{\"npa\": [[450.0, 353.0, 285.0, 332.0, 377.0, 268.0, 218.0, 387.0, 834.0, 508.0, 153.0, 42.0, 4.0, 1.0, 10.0, 17.0, 0.0, 4.0, 1.0, 2.0, 0.58, 0.5455, 0.64, 0.3284], [890.0, 450.0, 353.0, 285.0, 332.0, 377.0, 268.0, 218.0, 387.0, 834.0, 508.0, 153.0, 4.0, 1.0, 10.0, 18.0, 0.0, 4.0, 1.0, 2.0, 0.56, 0.5303, 0.64, 0.3284], [788.0, 890.0, 450.0, 353.0, 285.0, 332.0, 377.0, 268.0, 218.0, 387.0, 834.0, 508.0, 4.0, 1.0, 10.0, 19.0, 0.0, 4.0, 1.0, 2.0, 0.56, 0.5303, 0.68, 0.2985]]}" http://127.0.0.1:32789/score
```

### Calling web service ###


You can call the web service through az ml or curl. Here is the output by calling web service from az ml CLI

```
neeraj@mygpudsvm:~/notebooks$  az ml service run realtime -n bikews -d "{\"npa\": [[450.0, 353.0, 285.0, 332.0, 377.0, 268.0, 218.0, 387.0, 834.0, 508.0, 153.0, 42.0, 4.0, 1.0, 10.0, 17.0, 0.0, 4.0, 1.0, 2.0, 0.58, 0.5455, 0.64, 0.3284], [890.0, 450.0, 353.0, 285.0, 332.0, 377.0, 268.0, 218.0, 387.0, 834.0, 508.0, 153.0, 4.0, 1.0, 10.0, 18.0, 0.0, 4.0, 1.0, 2.0, 0.56, 0.5303, 0.64, 0.3284], [788.0, 890.0, 450.0, 353.0, 285.0, 332.0, 377.0, 268.0, 218.0, 387.0, 834.0, 508.0, 4.0, 1.0, 10.0, 19.0, 0.0, 4.0, 1.0, 2.0, 0.56, 0.5303, 0.68, 0.2985]]}"

   Scored Values
0     778.923218
1     804.909363
2     527.499268
```